
-- DROP TABLE users CASCADE;
CREATE TABLE users(
userId INTEGER NOT NULL
,userName VARCHAR(100) NOT NULL
,userEmail VARCHAR(100) DEFAULT NULL
,address VARCHAR(100) DEFAULT NULL

,PRIMARY KEY (userId)
);

-- DROP TABLE carts CASCADE;
CREATE TABLE carts(
ID INTEGER NOT NULL IDENTITY
,userId INTEGER NOT NULL
,cartType VARCHAR(100) NOT NULL
,PRIMARY KEY (ID)
);

-- ALTER TABLE carts
-- ADD CONSTRAINT FK_UsersCarts
-- FOREIGN KEY (userId) REFERENCES users(userId);


